### ISSUE TITLE
This app needs a better fucking name - comment with your ideas

### ISSUE THREAD

**Issue by dmoroni** [lholoubek/DemoFlight#15]
Here's my list:
- Captr (was my favorite, but the GoPro app is named Capture)
- Skyball
- Overhead
- GameRecord (already an app in the store named this)
- TopView
- Vdeo 
- VideoControl
- DroneSports
- MatchCapture
- GameCapture

**Comment by lholoubek** [comment]
PressBox (taken already :()
SkyBox
FieldCam
AerialEdge
SkyCoach
